import type { Locale } from "@/lib/i18n/config";

export const storiesCopy = {
  de: {
    nav: "Roots Stories",
    eyebrow: "GESCHICHTEN BEWAHREN",
    title: "Stimmen, die bleiben",
    intro:
      "Lade Großeltern und vertraute Familienmitglieder ein, eine Geschichte sicher für euer Roots Passport aufzunehmen.",
    back: "Zurück",
    requests: "Story-Anfragen",
    stories: "Eure Stories",
    noRequests: "Noch keine Story-Anfragen.",
    noStories: "Noch keine aufgenommenen Stories.",
    noChildren: "Erstelle zuerst ein Roots Passport für ein Kind.",
    premiumRequiredTitle: "Roots Stories ist eine Premium-Erweiterung",
    premiumRequiredBody:
      "Entdecke Familien und Villages weiterhin kostenlos. Für private Aufnahmen und KI-Verarbeitung ist Roots Family erforderlich.",
    managePlan: "Abo verwalten",
    providerUnavailableTitle:
      "Story-Verarbeitung vorübergehend nicht verfügbar",
    providerUnavailableBody:
      "Neue Aufnahme-Links sind pausiert, bis der sichere Verarbeitungsdienst wieder bereit ist.",
    create: "Story-Anfrage erstellen",
    question: "Frage oder Impuls",
    questionPlaceholder:
      "Erzählt uns von einem Moment, den ihr mit unserer Familie verbinden möchtet.",
    child: "Für welches Kind?",
    translation: "Übersetzung anfragen",
    noTranslation: "Keine Übersetzung",
    adaptation: "Kinderfreundliche Fassung anfragen",
    createLink: "Sicheren Link erstellen",
    creating: "Wird erstellt…",
    linkReady: "Sicherer Aufnahme-Link",
    copyLink: "Link kopieren",
    copied: "Kopiert",
    revoke: "Link widerrufen",
    revoking: "Wird widerrufen…",
    expires: "Gültig bis",
    pending: "Ausstehend",
    submitted: "Aufgenommen",
    revoked: "Widerrufen",
    expired: "Abgelaufen",
    titleLabel: "Story-Titel",
    originalLanguage: "Originalsprache",
    review: "Prüfen",
    approve: "Genehmigen",
    reject: "Ablehnen",
    addRoots: "Zum Roots Passport hinzufügen",
    added: "Zum Passport hinzugefügt",
    audio: "Original-Audio anhören",
    processing: "Wird verarbeitet…",
    failed: "Verarbeitung fehlgeschlagen",
    failedBody:
      "Die Verarbeitung wurde nicht abgeschlossen. Du kannst es erneut versuchen oder vorhandenen Text bearbeiten.",
    retry: "Verarbeitung erneut versuchen",
    saveEdits: "Änderungen speichern",
    statuses: {
      queued: "In Warteschlange",
      transcribing: "Wird transkribiert…",
      translating: "Wird übersetzt…",
      adapting: "Kinderfassung wird erstellt…",
    },
    languageNames: {
      de: "Deutsch",
      en: "Englisch",
      fr: "Französisch",
      es: "Spanisch",
      it: "Italienisch",
      pt: "Portugiesisch",
      wo: "Wolof",
      sw: "Swahili",
    },
    ready: "Bereit zur Prüfung",
    transcript: "Original-Transkript",
    translationText: "Übersetzung",
    adaptationText: "Kinderfreundliche Fassung",
    noAdaptation: "Noch keine Fassung vorhanden.",
    privacy:
      "Original-Audio und Texte bleiben privat. Nichts wird automatisch veröffentlicht.",
    recordTitle: "Eine Geschichte für eure Familie",
    defaultStoryTitle: "Eine Familiengeschichte",
    recording: "Aufnahme läuft",
    recordIntro:
      "Nimm dir Zeit. Du brauchst kein Konto; dieser Link ist nur für diese eine Aufnahme bestimmt.",
    record: "Aufnahme starten",
    stop: "Aufnahme beenden",
    upload: "Aufnahme senden",
    uploading: "Wird gesendet…",
    submittedBody: "Danke. Die Aufnahme wurde sicher übermittelt.",
    microphoneError:
      "Mikrofon konnte nicht gestartet werden. Du kannst eine Audiodatei auswählen.",
    file: "Audiodatei auswählen",
    invalidLink: "Dieser Aufnahme-Link ist nicht mehr verfügbar.",
    actionError:
      "Diese Aktion konnte nicht abgeschlossen werden. Bitte erneut versuchen.",
    types: { approved: "Genehmigt", rejected: "Abgelehnt" },
  },
  fr: {
    nav: "Roots Stories",
    eyebrow: "PRÉSERVER LES RÉCITS",
    title: "Des voix qui restent",
    intro:
      "Invitez des grands-parents ou proches de confiance à enregistrer une histoire pour votre Roots Passport, en toute sécurité.",
    back: "Retour",
    requests: "Demandes de récit",
    stories: "Vos récits",
    noRequests: "Aucune demande pour le moment.",
    noStories: "Aucun récit enregistré pour le moment.",
    noChildren: "Créez d’abord un Roots Passport pour un enfant.",
    premiumRequiredTitle: "Roots Stories est une option Premium",
    premiumRequiredBody:
      "La découverte des familles et Villages reste gratuite. Roots Family est requis pour les enregistrements privés et le traitement IA.",
    managePlan: "Gérer l’abonnement",
    providerUnavailableTitle:
      "Traitement des récits temporairement indisponible",
    providerUnavailableBody:
      "Les nouveaux liens d’enregistrement sont suspendus jusqu’au retour du service sécurisé.",
    create: "Créer une demande",
    question: "Question ou invitation",
    questionPlaceholder:
      "Racontez-nous un moment que vous aimeriez transmettre à notre famille.",
    child: "Pour quel enfant ?",
    translation: "Demander une traduction",
    noTranslation: "Pas de traduction",
    adaptation: "Demander une version adaptée aux enfants",
    createLink: "Créer le lien sécurisé",
    creating: "Création…",
    linkReady: "Lien d’enregistrement sécurisé",
    copyLink: "Copier le lien",
    copied: "Copié",
    revoke: "Révoquer le lien",
    revoking: "Révocation…",
    expires: "Valable jusqu’au",
    pending: "En attente",
    submitted: "Enregistré",
    revoked: "Révoqué",
    expired: "Expiré",
    titleLabel: "Titre du récit",
    originalLanguage: "Langue originale",
    review: "Réviser",
    approve: "Approuver",
    reject: "Refuser",
    addRoots: "Ajouter au Roots Passport",
    added: "Ajouté au Passport",
    audio: "Écouter l’audio original",
    processing: "Traitement…",
    failed: "Échec du traitement",
    failedBody:
      "Le traitement n’a pas abouti. Vous pouvez réessayer ou modifier le texte déjà disponible.",
    retry: "Réessayer le traitement",
    saveEdits: "Enregistrer les modifications",
    statuses: {
      queued: "En attente",
      transcribing: "Transcription…",
      translating: "Traduction…",
      adapting: "Adaptation pour enfant…",
    },
    languageNames: {
      de: "Allemand",
      en: "Anglais",
      fr: "Français",
      es: "Espagnol",
      it: "Italien",
      pt: "Portugais",
      wo: "Wolof",
      sw: "Swahili",
    },
    ready: "Prêt à réviser",
    transcript: "Transcription originale",
    translationText: "Traduction",
    adaptationText: "Version adaptée aux enfants",
    noAdaptation: "Aucune version n’est encore disponible.",
    privacy:
      "Audio et textes restent privés. Rien n’est publié automatiquement.",
    recordTitle: "Une histoire pour votre famille",
    defaultStoryTitle: "Une histoire de famille",
    recording: "Enregistrement en cours",
    recordIntro:
      "Prenez votre temps. Aucun compte n’est nécessaire ; ce lien est réservé à cet enregistrement.",
    record: "Commencer l’enregistrement",
    stop: "Arrêter l’enregistrement",
    upload: "Envoyer l’enregistrement",
    uploading: "Envoi…",
    submittedBody:
      "Merci. L’enregistrement a été transmis de manière sécurisée.",
    microphoneError:
      "Le microphone n’a pas pu démarrer. Vous pouvez choisir un fichier audio.",
    file: "Choisir un fichier audio",
    invalidLink: "Ce lien d’enregistrement n’est plus disponible.",
    actionError: "Cette action n’a pas pu être effectuée. Veuillez réessayer.",
    types: { approved: "Approuvé", rejected: "Refusé" },
  },
  en: {
    nav: "Roots Stories",
    eyebrow: "PRESERVE FAMILY STORIES",
    title: "Voices that remain",
    intro:
      "Invite grandparents and trusted family members to safely record a story for your Roots Passport.",
    back: "Back",
    requests: "Story requests",
    stories: "Your stories",
    noRequests: "No story requests yet.",
    noStories: "No recorded stories yet.",
    noChildren: "Create a Roots Passport for a child first.",
    premiumRequiredTitle: "Roots Stories is a premium enhancement",
    premiumRequiredBody:
      "Family and Village discovery remains free. Roots Family is required for private recordings and AI processing.",
    managePlan: "Manage plan",
    providerUnavailableTitle: "Story processing is temporarily unavailable",
    providerUnavailableBody:
      "New recording links are paused until the secure processing service is ready again.",
    create: "Create story request",
    question: "Question or prompt",
    questionPlaceholder:
      "Tell us about a moment you would like our family to carry forward.",
    child: "For which child?",
    translation: "Request a translation",
    noTranslation: "No translation",
    adaptation: "Request a child-friendly adaptation",
    createLink: "Create secure link",
    creating: "Creating…",
    linkReady: "Secure recording link",
    copyLink: "Copy link",
    copied: "Copied",
    revoke: "Revoke link",
    revoking: "Revoking…",
    expires: "Expires",
    pending: "Pending",
    submitted: "Recorded",
    revoked: "Revoked",
    expired: "Expired",
    titleLabel: "Story title",
    originalLanguage: "Original language",
    review: "Review",
    approve: "Approve",
    reject: "Reject",
    addRoots: "Add to Roots Passport",
    added: "Added to Passport",
    audio: "Listen to original audio",
    processing: "Processing…",
    failed: "Processing failed",
    failedBody:
      "Processing did not finish. You can retry it or edit any text already available.",
    retry: "Retry processing",
    saveEdits: "Save edits",
    statuses: {
      queued: "Queued",
      transcribing: "Transcribing…",
      translating: "Translating…",
      adapting: "Creating child-friendly version…",
    },
    languageNames: {
      de: "German",
      en: "English",
      fr: "French",
      es: "Spanish",
      it: "Italian",
      pt: "Portuguese",
      wo: "Wolof",
      sw: "Swahili",
    },
    ready: "Ready for review",
    transcript: "Original transcript",
    translationText: "Translation",
    adaptationText: "Child-friendly adaptation",
    noAdaptation: "No adaptation is available yet.",
    privacy:
      "Original audio and texts remain private. Nothing is published automatically.",
    recordTitle: "A story for your family",
    defaultStoryTitle: "A family story",
    recording: "Recording",
    recordIntro:
      "Take your time. No account is needed; this link is only for this recording.",
    record: "Start recording",
    stop: "Stop recording",
    upload: "Send recording",
    uploading: "Sending…",
    submittedBody: "Thank you. The recording was sent securely.",
    microphoneError:
      "The microphone could not start. You can choose an audio file instead.",
    file: "Choose an audio file",
    invalidLink: "This recording link is no longer available.",
    actionError: "This action could not be completed. Please try again.",
    types: { approved: "Approved", rejected: "Rejected" },
  },
} as const;

export type StoriesCopy = (typeof storiesCopy)[Locale];
export function getStoriesCopy(locale: Locale) {
  return storiesCopy[locale];
}
