import type { Locale } from "@/lib/i18n/config";

export const storiesCopy = {
  de: {
    nav: "Roots Stories",
    eyebrow: "GESCHICHTEN BEWAHREN",
    title: "Stimmen, die bleiben",
    intro:
      "Lade Großeltern und vertraute Familienmitglieder ein, eine Geschichte sicher für euer Roots Passport aufzunehmen.",
    back: "Zurück",
    requests: "Story-Anfragen",
    stories: "Eure Stories",
    noRequests: "Noch keine Story-Anfragen.",
    noStories: "Noch keine aufgenommenen Stories.",
    create: "Story-Anfrage erstellen",
    question: "Frage oder Impuls",
    questionPlaceholder:
      "Erzählt uns von einem Moment, den ihr mit unserer Familie verbinden möchtet.",
    child: "Für welches Kind?",
    translation: "Übersetzung anfragen",
    noTranslation: "Keine Übersetzung",
    adaptation: "Kinderfreundliche Fassung anfragen",
    createLink: "Sicheren Link erstellen",
    creating: "Wird erstellt…",
    linkReady: "Sicherer Aufnahme-Link",
    copyLink: "Link kopieren",
    copied: "Kopiert",
    revoke: "Link widerrufen",
    revoking: "Wird widerrufen…",
    expires: "Gültig bis",
    pending: "Ausstehend",
    submitted: "Aufgenommen",
    revoked: "Widerrufen",
    expired: "Abgelaufen",
    titleLabel: "Story-Titel",
    originalLanguage: "Originalsprache",
    review: "Prüfen",
    approve: "Genehmigen",
    reject: "Ablehnen",
    addRoots: "Zum Roots Passport hinzufügen",
    added: "Zum Passport hinzugefügt",
    audio: "Original-Audio anhören",
    processing: "Wird verarbeitet…",
    ready: "Bereit zur Prüfung",
    transcript: "Original-Transkript",
    translationText: "Übersetzung",
    adaptationText: "Kinderfreundliche Fassung",
    noAdaptation: "Noch keine Fassung vorhanden.",
    privacy:
      "Original-Audio und Texte bleiben privat. Nichts wird automatisch veröffentlicht.",
    recordTitle: "Eine Geschichte für eure Familie",
    recordIntro:
      "Nimm dir Zeit. Du brauchst kein Konto; dieser Link ist nur für diese eine Aufnahme bestimmt.",
    record: "Aufnahme starten",
    stop: "Aufnahme beenden",
    upload: "Aufnahme senden",
    uploading: "Wird gesendet…",
    submittedBody: "Danke. Die Aufnahme wurde sicher übermittelt.",
    microphoneError:
      "Mikrofon konnte nicht gestartet werden. Du kannst eine Audiodatei auswählen.",
    file: "Audiodatei auswählen",
    invalidLink: "Dieser Aufnahme-Link ist nicht mehr verfügbar.",
    actionError:
      "Diese Aktion konnte nicht abgeschlossen werden. Bitte erneut versuchen.",
    types: { approved: "Genehmigt", rejected: "Abgelehnt" },
  },
  fr: {
    nav: "Roots Stories",
    eyebrow: "PRÉSERVER LES RÉCITS",
    title: "Des voix qui restent",
    intro:
      "Invitez des grands-parents ou proches de confiance à enregistrer une histoire pour votre Roots Passport, en toute sécurité.",
    back: "Retour",
    requests: "Demandes de récit",
    stories: "Vos récits",
    noRequests: "Aucune demande pour le moment.",
    noStories: "Aucun récit enregistré pour le moment.",
    create: "Créer une demande",
    question: "Question ou invitation",
    questionPlaceholder:
      "Racontez-nous un moment que vous aimeriez transmettre à notre famille.",
    child: "Pour quel enfant ?",
    translation: "Demander une traduction",
    noTranslation: "Pas de traduction",
    adaptation: "Demander une version adaptée aux enfants",
    createLink: "Créer le lien sécurisé",
    creating: "Création…",
    linkReady: "Lien d’enregistrement sécurisé",
    copyLink: "Copier le lien",
    copied: "Copié",
    revoke: "Révoquer le lien",
    revoking: "Révocation…",
    expires: "Valable jusqu’au",
    pending: "En attente",
    submitted: "Enregistré",
    revoked: "Révoqué",
    expired: "Expiré",
    titleLabel: "Titre du récit",
    originalLanguage: "Langue originale",
    review: "Réviser",
    approve: "Approuver",
    reject: "Refuser",
    addRoots: "Ajouter au Roots Passport",
    added: "Ajouté au Passport",
    audio: "Écouter l’audio original",
    processing: "Traitement…",
    ready: "Prêt à réviser",
    transcript: "Transcription originale",
    translationText: "Traduction",
    adaptationText: "Version adaptée aux enfants",
    noAdaptation: "Aucune version n’est encore disponible.",
    privacy:
      "Audio et textes restent privés. Rien n’est publié automatiquement.",
    recordTitle: "Une histoire pour votre famille",
    recordIntro:
      "Prenez votre temps. Aucun compte n’est nécessaire ; ce lien est réservé à cet enregistrement.",
    record: "Commencer l’enregistrement",
    stop: "Arrêter l’enregistrement",
    upload: "Envoyer l’enregistrement",
    uploading: "Envoi…",
    submittedBody:
      "Merci. L’enregistrement a été transmis de manière sécurisée.",
    microphoneError:
      "Le microphone n’a pas pu démarrer. Vous pouvez choisir un fichier audio.",
    file: "Choisir un fichier audio",
    invalidLink: "Ce lien d’enregistrement n’est plus disponible.",
    actionError: "Cette action n’a pas pu être effectuée. Veuillez réessayer.",
    types: { approved: "Approuvé", rejected: "Refusé" },
  },
  en: {
    nav: "Roots Stories",
    eyebrow: "PRESERVE FAMILY STORIES",
    title: "Voices that remain",
    intro:
      "Invite grandparents and trusted family members to safely record a story for your Roots Passport.",
    back: "Back",
    requests: "Story requests",
    stories: "Your stories",
    noRequests: "No story requests yet.",
    noStories: "No recorded stories yet.",
    create: "Create story request",
    question: "Question or prompt",
    questionPlaceholder:
      "Tell us about a moment you would like our family to carry forward.",
    child: "For which child?",
    translation: "Request a translation",
    noTranslation: "No translation",
    adaptation: "Request a child-friendly adaptation",
    createLink: "Create secure link",
    creating: "Creating…",
    linkReady: "Secure recording link",
    copyLink: "Copy link",
    copied: "Copied",
    revoke: "Revoke link",
    revoking: "Revoking…",
    expires: "Expires",
    pending: "Pending",
    submitted: "Recorded",
    revoked: "Revoked",
    expired: "Expired",
    titleLabel: "Story title",
    originalLanguage: "Original language",
    review: "Review",
    approve: "Approve",
    reject: "Reject",
    addRoots: "Add to Roots Passport",
    added: "Added to Passport",
    audio: "Listen to original audio",
    processing: "Processing…",
    ready: "Ready for review",
    transcript: "Original transcript",
    translationText: "Translation",
    adaptationText: "Child-friendly adaptation",
    noAdaptation: "No adaptation is available yet.",
    privacy:
      "Original audio and texts remain private. Nothing is published automatically.",
    recordTitle: "A story for your family",
    recordIntro:
      "Take your time. No account is needed; this link is only for this recording.",
    record: "Start recording",
    stop: "Stop recording",
    upload: "Send recording",
    uploading: "Sending…",
    submittedBody: "Thank you. The recording was sent securely.",
    microphoneError:
      "The microphone could not start. You can choose an audio file instead.",
    file: "Choose an audio file",
    invalidLink: "This recording link is no longer available.",
    actionError: "This action could not be completed. Please try again.",
    types: { approved: "Approved", rejected: "Rejected" },
  },
} as const;

export type StoriesCopy = (typeof storiesCopy)[Locale];
export function getStoriesCopy(locale: Locale) {
  return storiesCopy[locale];
}
