import type { Locale } from "@/lib/i18n/config";

export const playdateCopy = {
  de: {
    heading: "Private Spieltreffen",
    intro:
      "Plane ein Treffen direkt mit einer verbundenen Familie. Die genaue Adresse bleibt bis zur Annahme geschützt.",
    propose: "Spieltreffen vorschlagen",
    title: "Titel",
    approximate: "Ungefähre Gegend",
    exact: "Genaue Adresse",
    exactHelp: "Nur die andere Familie sieht sie – und erst nach der Annahme.",
    options: "Terminvorschläge",
    adults: "Erwachsene",
    children: "Kinder",
    save: "Vorschlag senden",
    saving: "Wird gesendet…",
    accept: "Annehmen",
    decline: "Ablehnen",
    cancel: "Absagen",
    remind: "Erinnerung senden",
    read: "Als gelesen markieren",
    report: "Treffen melden",
    reportSend: "Meldung senden",
    reportReasons: {
      unsafe_location: "Unsicherer Ort",
      inappropriate_conduct: "Unangemessenes Verhalten",
      child_safety_concern: "Sorge um die Sicherheit eines Kindes",
      discrimination: "Diskriminierung",
      fraud: "Betrug",
      other: "Anderer Grund",
    },
    proposed: "Vorgeschlagen",
    accepted: "Angenommen",
    declined: "Abgelehnt",
    cancelled: "Abgesagt",
    incoming: "Diese Familie wartet auf deine Antwort.",
    outgoing: "Warte auf Antwort der anderen Familie.",
    selected: "Vereinbarter Termin",
    address: "Genaue Adresse",
    hidden: "Bis zur Annahme verborgen",
    attendees: "Teilnehmende",
    noPlaydates: "Noch keine privaten Spieltreffen.",
    error: "Das konnte nicht gespeichert werden. Bitte versuche es erneut.",
    reminder: "Neue Erinnerung zu diesem Treffen.",
    reportDetails: "Was ist passiert? (optional)",
  },
  fr: {
    heading: "Rencontres privées",
    intro:
      "Organisez une rencontre directement avec une famille connectée. L’adresse exacte reste protégée jusqu’à l’acceptation.",
    propose: "Proposer une rencontre",
    title: "Titre",
    approximate: "Zone approximative",
    exact: "Adresse exacte",
    exactHelp: "Seule l’autre famille la verra, après acceptation.",
    options: "Propositions de date",
    adults: "Adultes",
    children: "Enfants",
    save: "Envoyer la proposition",
    saving: "Envoi…",
    accept: "Accepter",
    decline: "Refuser",
    cancel: "Annuler",
    remind: "Envoyer un rappel",
    read: "Marquer comme lu",
    report: "Signaler la rencontre",
    reportSend: "Envoyer le signalement",
    reportReasons: {
      unsafe_location: "Lieu dangereux",
      inappropriate_conduct: "Comportement inapproprié",
      child_safety_concern: "Préoccupation pour la sécurité d’un enfant",
      discrimination: "Discrimination",
      fraud: "Fraude",
      other: "Autre motif",
    },
    proposed: "Proposée",
    accepted: "Acceptée",
    declined: "Refusée",
    cancelled: "Annulée",
    incoming: "Cette famille attend votre réponse.",
    outgoing: "En attente de la réponse de l’autre famille.",
    selected: "Date convenue",
    address: "Adresse exacte",
    hidden: "Masquée jusqu’à l’acceptation",
    attendees: "Participants",
    noPlaydates: "Aucune rencontre privée pour le moment.",
    error: "Impossible d’enregistrer. Réessayez.",
    reminder: "Nouveau rappel pour cette rencontre.",
    reportDetails: "Que s’est-il passé ? (facultatif)",
  },
  en: {
    heading: "Private playdates",
    intro:
      "Plan a meeting directly with a connected family. The exact address remains protected until acceptance.",
    propose: "Propose a playdate",
    title: "Title",
    approximate: "Approximate area",
    exact: "Exact address",
    exactHelp: "Only the other family can see it, and only after accepting.",
    options: "Date and time options",
    adults: "Adults",
    children: "Children",
    save: "Send proposal",
    saving: "Sending…",
    accept: "Accept",
    decline: "Decline",
    cancel: "Cancel",
    remind: "Send reminder",
    read: "Mark as read",
    report: "Report playdate",
    reportSend: "Send report",
    reportReasons: {
      unsafe_location: "Unsafe location",
      inappropriate_conduct: "Inappropriate conduct",
      child_safety_concern: "Child safety concern",
      discrimination: "Discrimination",
      fraud: "Fraud",
      other: "Other",
    },
    proposed: "Proposed",
    accepted: "Accepted",
    declined: "Declined",
    cancelled: "Cancelled",
    incoming: "This family is waiting for your response.",
    outgoing: "Waiting for the other family to respond.",
    selected: "Agreed time",
    address: "Exact address",
    hidden: "Hidden until acceptance",
    attendees: "Attendance",
    noPlaydates: "No private playdates yet.",
    error: "That could not be saved. Please try again.",
    reminder: "There is a new reminder for this playdate.",
    reportDetails: "What happened? (optional)",
  },
} satisfies Record<Locale, Record<string, string | Record<string, string>>>;

export const eventCoordinationCopy = {
  de: {
    heading: "Event-Abstimmung",
    intro:
      "Nur aktive Village-Mitglieder können diese Nachrichten lesen und schreiben.",
    empty: "Noch keine Nachrichten zu diesem Event.",
    label: "Nachricht",
    send: "Senden",
    sending: "Wird gesendet…",
    error: "Nachricht konnte nicht gesendet werden.",
    recurring: "Wiederholung",
    none: "Einmalig",
    weekly: "Wöchentlich",
    biweekly: "Alle zwei Wochen",
    monthly: "Monatlich",
    until: "Enddatum",
  },
  fr: {
    heading: "Coordination de l’événement",
    intro:
      "Seuls les membres actifs du Village peuvent lire et écrire ces messages.",
    empty: "Aucun message pour cet événement.",
    label: "Message",
    send: "Envoyer",
    sending: "Envoi…",
    error: "Le message n’a pas pu être envoyé.",
    recurring: "Récurrence",
    none: "Une fois",
    weekly: "Chaque semaine",
    biweekly: "Toutes les deux semaines",
    monthly: "Chaque mois",
    until: "Date de fin",
  },
  en: {
    heading: "Event coordination",
    intro: "Only active Village members can read and write these messages.",
    empty: "No messages for this event yet.",
    label: "Message",
    send: "Send",
    sending: "Sending…",
    error: "The message could not be sent.",
    recurring: "Repeat",
    none: "Once",
    weekly: "Weekly",
    biweekly: "Every two weeks",
    monthly: "Monthly",
    until: "End date",
  },
} satisfies Record<Locale, Record<string, string | Record<string, string>>>;
