import type { Locale } from "@/lib/i18n/config";

const copy = {
  de: {
    title: "Hilfe im Alltag",
    intro:
      "Stelle praktische Fragen im privaten Village oder teile eine konkrete Hilfe. Die Einträge bleiben chronologisch – ohne Likes, Ranking oder öffentlichen Feed.",
    create: "Beitrag erstellen",
    search: "Hilfe durchsuchen",
    searchPlaceholder: "Zum Beispiel Kita-Anmeldung",
    filter: "Filtern",
    allCategories: "Alle Kategorien",
    allTypes: "Alle Beitragstypen",
    open: "Offen",
    resolved: "Erledigt",
    allStatuses: "Offen und erledigt",
    empty: "Für diese Auswahl gibt es noch keine Beiträge.",
    titleLabel: "Kurzer Titel",
    bodyLabel: "Frage, Angebot oder Information",
    publish: "Im Village veröffentlichen",
    publishing: "Wird veröffentlicht…",
    privacy:
      "Ich bestätige, dass der Text keine Kindernamen, Schulen, genauen Adressen, Telefonnummern, E-Mail-Adressen oder Einwanderungsdokumente enthält.",
    privacyHint:
      "Teile nur allgemeine Erfahrungen. Dringende medizinische, rechtliche oder behördliche Fragen gehören zu einer qualifizierten Stelle.",
    reply: "Antworten",
    replyPlaceholder: "Teile eine praktische, respektvolle Antwort.",
    sendReply: "Antwort senden",
    close: "Als erledigt schließen",
    closed: "Erledigt",
    report: "Melden",
    reportReason: "Grund",
    reportDetails: "Optionale Hinweise für die Moderation",
    submitReport: "Meldung senden",
    reported: "Zur Prüfung gemeldet.",
    remove: "Entfernen",
    removeReason: "Moderationsgrund",
    actionError:
      "Die Aktion konnte nicht abgeschlossen werden. Prüfe auch, ob Kontakt- oder andere geschützte Daten enthalten sind.",
    familyBy: "Von {family}",
    replies: "{count} Antworten",
    contentTypes: {
      question: "Frage",
      help_request: "Hilfegesuch",
      recommendation_request: "Empfehlung gesucht",
      resource: "Ressource",
      announcement: "Hinweis",
      offer_of_help: "Hilfsangebot",
    },
    categories: {
      kita: "Kita",
      school: "Schule",
      german_language: "Deutsch",
      administration: "Behörden",
      immigration_integration: "Migration und Integration",
      healthcare_navigation: "Orientierung im Gesundheitswesen",
      local_family_services: "Lokale Familienangebote",
      transport: "Mobilität",
      childcare_coordination: "Kinderbetreuung koordinieren",
      local_recommendations: "Lokale Empfehlungen",
      other_practical_support: "Andere praktische Hilfe",
    },
    reportReasons: {
      privacy_exposure: "Private Daten offengelegt",
      unsafe_advice: "Gefährlicher Rat",
      harassment: "Belästigung",
      discrimination: "Diskriminierung",
      fraud: "Betrug",
      child_safety_concern: "Kinderschutz",
      outdated_or_misleading: "Veraltet oder irreführend",
      other: "Sonstiges",
    },
    moderationReasons: {
      unsafe: "Unsicher",
      privacy: "Datenschutz",
      outdated: "Veraltet",
      duplicate: "Duplikat",
      other: "Sonstiges",
    },
  },
  fr: {
    title: "Entraide quotidienne",
    intro:
      "Posez une question pratique dans le Village privé ou proposez une aide concrète. Les publications restent chronologiques, sans likes, classement ni fil public.",
    create: "Créer une publication",
    search: "Rechercher dans l’entraide",
    searchPlaceholder: "Par exemple, inscription à la Kita",
    filter: "Filtrer",
    allCategories: "Toutes les catégories",
    allTypes: "Tous les types",
    open: "Ouvert",
    resolved: "Résolu",
    allStatuses: "Ouvert et résolu",
    empty: "Aucune publication ne correspond à ces critères.",
    titleLabel: "Titre court",
    bodyLabel: "Question, proposition ou information",
    publish: "Publier dans le Village",
    publishing: "Publication…",
    privacy:
      "Je confirme que le texte ne contient aucun nom d’enfant, école, adresse exacte, numéro de téléphone, e-mail ou document d’immigration.",
    privacyHint:
      "Partagez uniquement des expériences générales. Une question médicale, juridique ou administrative urgente nécessite un service qualifié.",
    reply: "Répondre",
    replyPlaceholder: "Partagez une réponse pratique et respectueuse.",
    sendReply: "Envoyer la réponse",
    close: "Marquer comme résolu",
    closed: "Résolu",
    report: "Signaler",
    reportReason: "Motif",
    reportDetails: "Informations facultatives pour la modération",
    submitReport: "Envoyer le signalement",
    reported: "Envoyé pour examen.",
    remove: "Retirer",
    removeReason: "Motif de modération",
    actionError:
      "L’action n’a pas abouti. Vérifiez notamment l’absence de coordonnées ou de données protégées.",
    familyBy: "Par {family}",
    replies: "{count} réponses",
    contentTypes: {
      question: "Question",
      help_request: "Demande d’aide",
      recommendation_request: "Demande de recommandation",
      resource: "Ressource",
      announcement: "Annonce",
      offer_of_help: "Proposition d’aide",
    },
    categories: {
      kita: "Kita",
      school: "École",
      german_language: "Allemand",
      administration: "Administration",
      immigration_integration: "Immigration et intégration",
      healthcare_navigation: "Orientation dans le système de santé",
      local_family_services: "Services familiaux locaux",
      transport: "Transport",
      childcare_coordination: "Coordination de garde",
      local_recommendations: "Recommandations locales",
      other_practical_support: "Autre aide pratique",
    },
    reportReasons: {
      privacy_exposure: "Données privées exposées",
      unsafe_advice: "Conseil dangereux",
      harassment: "Harcèlement",
      discrimination: "Discrimination",
      fraud: "Fraude",
      child_safety_concern: "Protection de l’enfant",
      outdated_or_misleading: "Obsolète ou trompeur",
      other: "Autre",
    },
    moderationReasons: {
      unsafe: "Dangereux",
      privacy: "Confidentialité",
      outdated: "Obsolète",
      duplicate: "Doublon",
      other: "Autre",
    },
  },
  en: {
    title: "Everyday support",
    intro:
      "Ask a practical question inside the private Village or offer concrete help. Posts stay chronological—without likes, ranking, or a public feed.",
    create: "Create a post",
    search: "Search support",
    searchPlaceholder: "For example, Kita registration",
    filter: "Filter",
    allCategories: "All categories",
    allTypes: "All post types",
    open: "Open",
    resolved: "Resolved",
    allStatuses: "Open and resolved",
    empty: "No posts match these filters yet.",
    titleLabel: "Short title",
    bodyLabel: "Question, offer, or information",
    publish: "Publish inside the Village",
    publishing: "Publishing…",
    privacy:
      "I confirm this text contains no child names, schools, exact addresses, phone numbers, email addresses, or immigration documents.",
    privacyHint:
      "Share general experience only. Urgent medical, legal, or official matters need a qualified service.",
    reply: "Reply",
    replyPlaceholder: "Share a practical and respectful response.",
    sendReply: "Send reply",
    close: "Close as resolved",
    closed: "Resolved",
    report: "Report",
    reportReason: "Reason",
    reportDetails: "Optional context for moderators",
    submitReport: "Send report",
    reported: "Sent for review.",
    remove: "Remove",
    removeReason: "Moderation reason",
    actionError:
      "The action could not be completed. Check that contact or other protected details were not included.",
    familyBy: "By {family}",
    replies: "{count} replies",
    contentTypes: {
      question: "Question",
      help_request: "Help request",
      recommendation_request: "Recommendation request",
      resource: "Resource",
      announcement: "Announcement",
      offer_of_help: "Offer of help",
    },
    categories: {
      kita: "Kita",
      school: "School",
      german_language: "German language",
      administration: "Administration",
      immigration_integration: "Immigration and integration",
      healthcare_navigation: "Healthcare navigation",
      local_family_services: "Local family services",
      transport: "Transport",
      childcare_coordination: "Childcare coordination",
      local_recommendations: "Local recommendations",
      other_practical_support: "Other practical support",
    },
    reportReasons: {
      privacy_exposure: "Private information exposed",
      unsafe_advice: "Unsafe advice",
      harassment: "Harassment",
      discrimination: "Discrimination",
      fraud: "Fraud",
      child_safety_concern: "Child-safety concern",
      outdated_or_misleading: "Outdated or misleading",
      other: "Other",
    },
    moderationReasons: {
      unsafe: "Unsafe",
      privacy: "Privacy",
      outdated: "Outdated",
      duplicate: "Duplicate",
      other: "Other",
    },
  },
} as const;

export const getSupportCopy = (locale: Locale) => copy[locale];
export const supportCopyParity = copy;
