begin;

-- These editorial translations are intentionally unpublished. They provide a
-- complete, versioned review queue for the German and French mission catalogue;
-- only a cultural reviewer may promote a record to `reviewed`.
do $drafts$
declare
  mission_draft jsonb;
  step_draft jsonb;
  content jsonb := $content$
[
  {"slug":"five-greetings-from-cameroon","locale":"de","title":"Fünf Familiengrüße weitergeben","summary":"Lernt Grüße mit einer vertrauten Person und übt, wann sie verwendet werden.","description":"Wählt Grüße, die mit den kamerunischen Wurzeln eurer Familie verbunden sind. Haltet die Aussprache nur mit Erlaubnis fest, lernt, wer jeden Gruß verwendet, und behandelt keine Sprache als stellvertretend für ganz Kamerun.","context":"Kamerun ist mehrsprachig. Diese landesbezogene Aktivität lädt jede Familie ein, die konkrete Sprache und Gemeinschaft hinter jedem Gruß zu benennen, statt unterschiedliche Traditionen miteinander zu vermischen.","materials":["Papier oder eine private Familiennotiz","Eine vertraute sprechende Person oder eine von der Familie erlaubte Aufnahme","Bleistift oder Buntstifte"],"guidance":"Die sprechende Person entscheidet, was aufgenommen werden darf. Setzt Kinder nicht unter Druck, ungewohnte Laute vorzuführen, und ladet keine Stimme einer anderen Person ohne Einwilligung hoch.","attribution":"Nennt die Person, Sprache und Gemeinschaft, von der jeder Gruß stammt, und verwendet nur den Namen oder die Beziehung, die geteilt werden darf.","reflection":"Welchen Gruß möchtet ihr behalten, wer hat ihn euch beigebracht und wann wird eure Familie ihn verwenden?","steps":[{"position":1,"title":"Fragen und zuordnen","description":"Bittet eine vertraute Person um fünf Grüße und notiert zu jedem Sprache, Gemeinschaft und passende Situation."},{"position":2,"title":"Mit Erlaubnis zuhören","description":"Hört langsam zu und achtet auf Aussprache und Tonfall; nehmt nur auf, wenn die Person ausdrücklich zustimmt."},{"position":3,"title":"Im Zusammenhang üben","description":"Spielt Situationen nach, in denen die Grüße passen, und lasst alle ohne Druck teilnehmen."},{"position":4,"title":"Weitergeben","description":"Verwendet einen Gruß mit einer vertrauten verwandten Person und haltet fest, was eure Familie bewahren möchte."}]},
  {"slug":"five-greetings-from-cameroon","locale":"fr","title":"Transmettre cinq salutations familiales","summary":"Apprenez des salutations avec une personne de confiance et exercez-vous à les employer au bon moment.","description":"Choisissez des salutations liées aux racines camerounaises de votre famille. Notez la prononciation seulement avec autorisation, apprenez qui emploie chaque salutation et ne présentez aucune langue comme représentative de tout le Cameroun.","context":"Le Cameroun est multilingue. Cette activité à l'échelle du pays invite chaque famille à nommer la langue et la communauté précises derrière chaque salutation, plutôt que de mélanger des traditions distinctes.","materials":["Papier ou note familiale privée","Personne de confiance ou enregistrement autorisé par la famille","Crayon ou crayons de couleur"],"guidance":"La personne qui parle choisit ce qui peut être enregistré. Ne forcez jamais un enfant à reproduire des sons inconnus et ne téléversez pas la voix d'une autre personne sans son consentement.","attribution":"Citez la personne, la langue et la communauté qui ont transmis chaque salutation, en n'utilisant que le nom ou le lien qu'elles acceptent de partager.","reflection":"Quelle salutation voulez-vous retenir, qui vous l'a enseignée et quand votre famille l'utilisera-t-elle ?","steps":[{"position":1,"title":"Demander et identifier","description":"Demandez à une personne de confiance cinq salutations et notez pour chacune la langue, la communauté et le contexte."},{"position":2,"title":"Écouter avec permission","description":"Écoutez lentement la prononciation et le ton ; enregistrez seulement avec un accord explicite."},{"position":3,"title":"S'exercer en contexte","description":"Jouez les situations où chaque salutation convient et laissez chacun participer à son aise."},{"position":4,"title":"Transmettre","description":"Utilisez une salutation avec un proche de confiance et retenez ce que votre famille souhaite garder."}]},
  {"slug":"family-recipe-table","locale":"de","title":"Ein Rezept kochen und seine Geschichte verfolgen","summary":"Bereitet ein Familiengericht zu und entdeckt die Geschichte seiner Zutaten, seines Namens und seiner Erinnerungen.","description":"Wählt ein kamerunisches Familienrezept, kocht gemeinsam und unterscheidet eure Haushaltsversion von den vielen regionalen und gemeinschaftlichen Varianten, die denselben Namen tragen können.","context":"Essgewohnheiten unterscheiden sich nach Region, Gemeinschaft, Glauben, Jahreszeit und Haushalt. Die Quelle der eigenen Familie steht im Mittelpunkt; kein Rezept wird als die endgültige kamerunische Version dargestellt.","materials":["Ein Familienrezept oder Gespräch mit einer vertrauten kochenden Person","Zutaten und altersgerechte Küchenwerkzeuge","Papier oder eine private Familiennotiz"],"guidance":"Eine erwachsene Person übernimmt Hitze, Messer und Allergien. Fragt, bevor ihr Rezept oder Geschichte einer anderen Person bewahrt, und bewertet Ersatzprodukte in Deutschland nicht als weniger authentisch.","attribution":"Nennt mit Erlaubnis die verwandte Person, kochende Person, den Haushalt oder die Gemeinschaft als Quelle und unterscheidet ihre Version von Anpassungen eurer Familie.","reflection":"Welchen Geschmack, Menschen oder Ort soll eure Familie mit diesem Rezept verbinden, und was habt ihr angepasst?","steps":[{"position":1,"title":"Quelle wählen","description":"Fragt, wer das Rezept vermittelt hat, wo eure Familienversion zubereitet wird und wann sie serviert wird."},{"position":2,"title":"Sicher zubereiten","description":"Verteilt altersgerechte Aufgaben; eine erwachsene Person übernimmt Hitze, Messer und Allergiekontrollen."},{"position":3,"title":"Eine Zutat verfolgen","description":"Wählt eine Zutat und sprecht darüber, wo die Familie sie in Deutschland findet und welche Ersatzmöglichkeiten es gibt."},{"position":4,"title":"Erinnerung teilen","description":"Esst zusammen und notiert Quelle, eine Anpassung und eine Familienerinnerung."}]},
  {"slug":"family-recipe-table","locale":"fr","title":"Cuisiner une recette et suivre son histoire","summary":"Préparez un plat familial et découvrez l'histoire de ses ingrédients, de son nom et de ses souvenirs.","description":"Choisissez une recette familiale camerounaise, cuisinez-la ensemble et distinguez la version de votre foyer des nombreuses variantes régionales ou communautaires pouvant porter le même nom.","context":"Les traditions culinaires varient selon les régions, les communautés, les croyances, les saisons et les foyers. La source de la famille est centrale ; aucune recette n'est présentée comme la version camerounaise définitive.","materials":["Recette familiale ou échange avec une personne qui cuisine de confiance","Ingrédients et ustensiles adaptés à l'âge","Papier ou note familiale privée"],"guidance":"Un adulte gère la chaleur, les couteaux et les allergies. Demandez avant de conserver la recette ou l'histoire d'autrui et ne jugez pas les substitutions faites en Allemagne comme moins authentiques.","attribution":"Nommez, avec permission, le proche, la personne qui cuisine, le foyer ou la communauté source et distinguez sa version des adaptations de votre famille.","reflection":"Quelle saveur, personne ou quel lieu votre famille doit-elle retenir de cette recette, et qu'avez-vous adapté ?","steps":[{"position":1,"title":"Choisir la source","description":"Demandez qui a transmis la recette, où la version familiale est préparée et quand elle est servie."},{"position":2,"title":"Préparer en sécurité","description":"Répartissez des tâches adaptées à l'âge ; un adulte gère chaleur, couteaux et allergies."},{"position":3,"title":"Suivre un ingrédient","description":"Choisissez un ingrédient et discutez de son accès en Allemagne et des substitutions possibles."},{"position":4,"title":"Partager le souvenir","description":"Mangez ensemble et notez la source, une adaptation et un souvenir familial."}]},
  {"slug":"map-a-family-journey","locale":"de","title":"Kamerun durch Familienverbindungen kartieren","summary":"Erkundet Regionen und Orte über Menschen, Sprachen und Erinnerungen, die eure Familie damit verbinden.","description":"Verwendet eine einfache Karte, um Kamerun, Nachbarländer und einige familienverbundene Orte zu finden. Haltet genaue Wohnorte und Reisedetails privat und lernt, dass Geografie und kulturelle Identität zusammenhängen, aber nicht dasselbe sind.","context":"Dies ist eine landesbezogene Geografie-Aktivität. Sie bietet Raum für Regionen, Sprachen, Städte und ländliche Orte, ohne Verwaltungsgrenzen mit der Identität einer Person gleichzusetzen.","materials":["Eine Papierkarte oder ein Offline-Kartenbild","Papier, Bleistifte und ablösbare Markierungen","Von der Familie erlaubte Ortsnamen"],"guidance":"Verwendet Stadt- oder Regionsnamen statt privater Adressen. Erwachsene entscheiden, über welche Migrations- oder Reiseerinnerungen gesprochen und welche gespeichert werden dürfen.","attribution":"Nennt die Familie oder vertraute Quelle für Ortswissen und kennzeichnet unsichere Erinnerungen als Fragen statt als Tatsachen.","reflection":"Welcher Ort auf der Karte ist für eure Familie wichtig, und welche Frage möchtet ihr dazu stellen?","steps":[{"position":1,"title":"Die weitere Region finden","description":"Findet Kamerun, seine Nachbarländer und Deutschland, ohne Orte als mehr oder weniger wichtig einzuordnen."},{"position":2,"title":"Familienorte ergänzen","description":"Markiert nur erlaubte Städte, Regionen oder Landschaften; niemals eine private Adresse."},{"position":3,"title":"Sprache und Ort verbinden","description":"Ergänzt Sprachen oder Gemeinschaften nur, wenn eure Quelle diese Verbindung herstellt, und beachtet, dass Menschen umziehen."},{"position":4,"title":"Eine Kartengeschichte erzählen","description":"Wählt einen Ort, teilt eine Erinnerung oder Frage und speichert eine datensparsame Reflexion."}]},
  {"slug":"map-a-family-journey","locale":"fr","title":"Cartographier le Cameroun par les liens familiaux","summary":"Explorez régions et lieux à travers les personnes, langues et souvenirs auxquels votre famille les relie.","description":"Utilisez une carte simple pour situer le Cameroun, les pays voisins et quelques lieux liés à votre famille. Gardez privés les domiciles et trajets précis, et apprenez que géographie et identité culturelle sont liées sans être interchangeables.","context":"Il s'agit d'une activité de géographie à l'échelle du pays. Elle fait place aux régions, langues, villes et espaces ruraux sans confondre frontières administratives et identité d'une personne.","materials":["Carte papier ou image de carte hors ligne","Papier, crayons et marqueurs amovibles","Noms de lieux approuvés par la famille"],"guidance":"Utilisez des noms de villes ou de régions plutôt que des adresses privées. Les adultes décident quels souvenirs de migration ou de voyage peuvent être abordés et conservés.","attribution":"Attribuez les connaissances sur les lieux à la famille ou à la source de confiance et présentez les souvenirs incertains comme des questions, non des faits.","reflection":"Quel lieu de la carte compte pour votre famille et quelle question aimeriez-vous poser à son sujet ?","steps":[{"position":1,"title":"Situer la région","description":"Repérez le Cameroun, ses pays voisins et l'Allemagne sans classer les lieux par importance."},{"position":2,"title":"Ajouter les lieux familiaux","description":"Marquez seulement des villes, régions ou paysages approuvés ; jamais une adresse privée."},{"position":3,"title":"Relier langue et lieu","description":"Ajoutez des langues ou communautés seulement lorsque votre source établit ce lien, en rappelant que les personnes se déplacent."},{"position":4,"title":"Raconter une histoire de carte","description":"Choisissez un lieu, partagez un souvenir ou une question et conservez une réflexion respectueuse de la vie privée."}]},
  {"slug":"family-song-and-rhythm","locale":"de","title":"Ein Duala-Lied, einen Rhythmus oder eine Bewegung lernen","summary":"Folgt einer vertrauten Duala-Familien- oder Gemeinschaftsquelle und lernt, wie ein Stück verwendet und erinnert wird.","description":"Wählt ein Lied, einen Rhythmus oder eine Bewegung, die eure vertraute Quelle als Duala bezeichnet. Lernt Anlass und Bedeutung, bevor ihr eine familiäre Antwort entwickelt, und lasst ein Beispiel nicht für alle Duala-Personen stehen.","context":"Duala-Musik und Bewegungspraktiken sind lebendig und vielfältig. Diese Aktivität stützt sich bewusst auf eine benannte Familien- oder Gemeinschaftsquelle statt auf eine angeblich allgemeingültige Aufführung.","materials":["Ein von der Familie erlaubtes Lied oder eine Vorführung","Ein sicherer freier Platz","Optional einfache Percussion aus dem Haushalt"],"guidance":"Achtet auf Lautstärke, Bewegungsraum und körperliche Zugänglichkeit. Fragt vor Aufnahme, Kopie oder Teilen von Stimme, Bild oder Aufführung einer Person.","attribution":"Nennt mit Erlaubnis die Duala-Quelle und den Anlass oder Kontext, den sie beschreibt; bezeichnet kommerzielle Aufnahmen nicht als Familienmaterial.","reflection":"Was wollte eure Quelle, dass ihr über diesen Klang oder diese Bewegung versteht, und wie werdet ihr sie nennen?","steps":[{"position":1,"title":"Nach dem Anlass fragen","description":"Erfahrt, wer das Stück geteilt hat, wann es verwendet wird und ob etwas privat bleiben soll."},{"position":2,"title":"Zuhören und beobachten","description":"Achtet auf Rhythmus, Worte oder Bewegung, bevor ihr sie ausprobiert, und fragt nach unbekannten Bedeutungen."},{"position":3,"title":"Gemeinsam antworten","description":"Entwickelt eine altersgerechte Familienantwort, ohne eine formelle Aufführung nachzuahmen."},{"position":4,"title":"Quelle nennen","description":"Haltet fest, was ihr gelernt habt, welche Nennung erlaubt ist und was nicht geteilt werden darf."}]},
  {"slug":"family-song-and-rhythm","locale":"fr","title":"Apprendre un chant, un rythme ou un mouvement duala","summary":"Suivez une source familiale ou communautaire duala de confiance pour comprendre l'usage et le souvenir d'une pièce.","description":"Choisissez un chant, un rythme ou un mouvement que votre source de confiance identifie comme duala. Apprenez son contexte et son sens avant d'y répondre en famille, sans faire d'un exemple le représentant de toutes les personnes duala.","context":"Les pratiques musicales et gestuelles duala sont vivantes et diverses. Cette activité s'appuie délibérément sur une source familiale ou communautaire nommée plutôt que de prescrire une performance prétendument universelle.","materials":["Chant ou démonstration approuvé par la famille","Espace libre et sûr","Percussions domestiques facultatives"],"guidance":"Vérifiez le volume, l'espace de mouvement et l'accessibilité physique. Demandez avant d'enregistrer, copier ou partager la voix, l'image ou la performance d'une personne.","attribution":"Nommez la source duala et l'occasion ou le contexte qu'elle décrit, avec son accord ; ne présentez pas des enregistrements commerciaux comme du matériel familial.","reflection":"Que souhaitait vous faire comprendre votre source sur ce son ou ce mouvement, et comment la créditerez-vous ?","steps":[{"position":1,"title":"Demander le contexte","description":"Apprenez qui a partagé la pièce, quand elle est utilisée et si une partie doit rester privée."},{"position":2,"title":"Écouter et observer","description":"Observez rythme, mots ou gestes avant d'essayer ; posez des questions sur les sens inconnus."},{"position":3,"title":"Répondre ensemble","description":"Créez une réponse familiale adaptée à l'âge sans prétendre reproduire une performance formelle."},{"position":4,"title":"Citer la source","description":"Notez ce que vous avez appris, l'attribution autorisée et ce qui ne doit pas être partagé."}]},
  {"slug":"teach-a-family-game","locale":"de","title":"Ein traditionelles Spiel aus eurer Familie vermitteln","summary":"Lernt ein Spiel über eine Familienquelle, einschließlich seines Namens, seiner Regeln und Varianten.","description":"Bittet eine verwandte oder vertraute Person aus der Gemeinschaft, euch ein Spiel zu zeigen, das sie mit ihrer Kindheit in Kamerun verbindet. Vergleicht Regelvarianten respektvoll und passt nur für Sicherheit, Zugang und vorhandenen Raum an.","context":"Spiele wandern und verändern sich zwischen Haushalten und Gemeinschaften. Diese Aktivität dokumentiert die Version einer Person, statt ohne Belege einen einzigen Ursprung oder feste nationale Regeln zu behaupten.","materials":["Eine vertraute Person, die das Spiel kennt","Eine sichere Spielfläche","Einfache Spielmaterialien, die von der Quelle ausgewählt werden"],"guidance":"Eine erwachsene Person prüft Raum, Material, Körperkontakt und Alterseignung. Macht Anpassungen für Zugänglichkeit offen und verspottet keine Namen, Akzente oder unbekannten Regeln.","attribution":"Haltet fest, wer diese Version beigebracht hat, wie sie das Spiel nennt und welche Gemeinschaft oder welchen Ort sie nennen möchte.","reflection":"Welche Regel, welches Wort oder welcher Moment machte diese Version für die lehrende Person besonders?","steps":[{"position":1,"title":"Lehrperson einladen","description":"Bittet eine vertraute Person, ein Spiel auszuwählen und seinen Namen sowie den Spielort zu erklären."},{"position":2,"title":"Sichere Regeln festlegen","description":"Prüft den Spielbereich, zeigt die Regeln und vereinbart Anpassungen für Alter oder Zugang."},{"position":3,"title":"Zwei Runden spielen","description":"Probiert die vermittelte Version und besprecht Regelunterschiede, statt Familienerinnerungen zu korrigieren."},{"position":4,"title":"Version bewahren","description":"Speichert erlaubte Nennung, die verwendeten Regeln und einen Lieblingsmoment."}]},
  {"slug":"teach-a-family-game","locale":"fr","title":"Transmettre un jeu traditionnel de votre famille","summary":"Apprenez un jeu auprès d'une source familiale, avec son nom local, ses règles et ses variantes.","description":"Demandez à un proche ou à une personne communautaire de confiance de vous apprendre un jeu qu'elle associe à son enfance au Cameroun. Comparez les variantes de règles avec respect et n'adaptez que pour la sécurité, l'accès et l'espace disponible.","context":"Les jeux voyagent et évoluent entre foyers et communautés. Cette activité documente la version d'une personne au lieu d'attribuer sans preuve une origine unique ou des règles nationales fixes.","materials":["Personne de confiance qui connaît le jeu","Espace de jeu sûr","Éléments simples choisis par la source"],"guidance":"Un adulte vérifie l'espace, le matériel, les contacts et l'âge approprié. Adaptez ouvertement pour l'accessibilité et ne vous moquez jamais des noms, accents ou règles inconnues.","attribution":"Notez qui a transmis cette version, le nom qu'elle lui donne et tout lien communautaire ou géographique qu'elle accepte de nommer.","reflection":"Quelle règle, quel mot ou quel moment rendait cette version spéciale pour la personne qui vous l'a enseignée ?","steps":[{"position":1,"title":"Inviter la personne qui enseigne","description":"Demandez à une personne de confiance de choisir un jeu et d'expliquer son nom et le lieu où elle y jouait."},{"position":2,"title":"Fixer des règles sûres","description":"Vérifiez l'espace, montrez les règles et convenez d'adaptations d'âge ou d'accessibilité."},{"position":3,"title":"Jouer deux manches","description":"Essayez la version transmise, puis discutez des différences sans corriger les souvenirs familiaux."},{"position":4,"title":"Garder la version","description":"Conservez l'attribution autorisée, les règles utilisées et un moment préféré."}]},
  {"slug":"bassa-family-folktale","locale":"de","title":"Eine Bassa-Familiengeschichte behutsam weitertragen","summary":"Hört einer Geschichte aus einer vertrauten Bassa-Quelle zu und bewahrt Erzähler, Kontext und offene Fragen.","description":"Bittet eine vertraute Bassa-verwandte Person oder eine Person aus der Gemeinschaft, ein Märchen oder eine Familiengeschichte auszuwählen, die sie teilen möchte. Achtet darauf, wie diese Person die Geschichte gelernt hat und versteht, statt nach einer einzigen maßgeblichen Version zu suchen.","context":"Mündliche Geschichten können mehrere Erzähler, Versionen und Erlaubnisse haben. Diese Bassa-bezogene Aktivität macht die erzählende Person und ihre Darstellung sichtbar und veröffentlicht kein heiliges, eingeschränktes oder privat gehaltenes Material.","materials":["Eine vertraute erzählende Person","Einen ruhigen Ort zum Zuhören","Papier oder eine private Aufnahme mit Erlaubnis"],"guidance":"Die erzählende Person entscheidet, ob aufgenommen und was weitererzählt werden darf. Hört auf, wenn die Geschichte beängstigend oder nicht altersgerecht ist, und erfindet keine fehlende kulturelle Bedeutung.","attribution":"Nennt die erzählende Person und den Bassa-Kontext, den sie nennt, in ihrer bevorzugten Formulierung und nur mit erlaubten Identitätsangaben.","reflection":"Wer erzählte diese Version, worüber lässt sie euch nachdenken und welche Erlaubnis gab die Person zum Bewahren?","steps":[{"position":1,"title":"Erlaubnis vereinbaren","description":"Fragt, was gehört, aufgenommen, weitererzählt oder nur in der Familie behalten werden darf."},{"position":2,"title":"Ohne Unterbrechung zuhören","description":"Hört die ganze Geschichte und bewahrt Fragen bis zum Ende auf, außer die Person lädt dazu ein."},{"position":3,"title":"Nach dieser Version fragen","description":"Erfahrt, wann die Person sie hörte, was sie ihr bedeutet und ob andere Versionen bekannt sind."},{"position":4,"title":"Reflektieren, nicht vereinfachen","description":"Speichert die erlaubte Nennung, eine Reflexion und Grenzen für späteres Teilen."}]},
  {"slug":"bassa-family-folktale","locale":"fr","title":"Porter avec soin un récit familial bassa","summary":"Écoutez une histoire d'une source bassa de confiance et conservez la personne qui raconte, le contexte et les questions ouvertes.","description":"Invitez un proche bassa ou une personne communautaire de confiance à choisir un conte ou un récit familial qu'elle souhaite partager. Intéressez-vous à la manière dont cette personne l'a appris et le comprend, plutôt qu'à une version unique faisant autorité.","context":"Les récits oraux peuvent avoir plusieurs personnes qui racontent, versions et permissions. Cette activité centrée sur les Bassa garde visible la personne qui raconte et son récit, et ne publie aucun contenu sacré, restreint ou privé.","materials":["Personne de confiance qui raconte","Lieu calme pour écouter","Papier ou enregistrement privé avec permission"],"guidance":"La personne qui raconte décide si l'enregistrement et la répétition sont permis. Arrêtez si le récit est effrayant ou inadapté à l'âge et n'inventez jamais de sens culturel absent.","attribution":"Citez la personne qui raconte et le contexte bassa qu'elle nomme, selon ses propres termes et avec les seuls détails d'identité autorisés.","reflection":"Qui a raconté cette version, que vous a-t-elle fait vous demander et quelle permission a été donnée pour la conserver ?","steps":[{"position":1,"title":"Convenir de la permission","description":"Demandez ce qui peut être écouté, enregistré, raconté ou gardé seulement dans la famille."},{"position":2,"title":"Écouter sans interrompre","description":"Écoutez d'abord le récit entier et gardez les questions pour la fin, sauf invitation contraire."},{"position":3,"title":"Questionner cette version","description":"Demandez quand la personne l'a entendue, ce qu'elle signifie pour elle et si d'autres versions existent."},{"position":4,"title":"Réfléchir sans aplatir","description":"Conservez l'attribution permise, une réflexion et les limites de partage futur."}]},
  {"slug":"cameroon-history-family-timeline","locale":"de","title":"Eine kamerunische Familien-Zeitleiste erstellen","summary":"Stellt Familienerinnerungen neben sorgfältig belegte öffentliche Ereignisse, ohne eine Familiengeschichte zur nationalen Geschichte zu machen.","description":"Wählt einen kurzen Zeitraum mit Bezug zu eurer Familie, ergänzt zwei oder drei öffentliche historische Ereignisse aus einer vertrauenswürdigen Museums-, Archiv-, Bibliotheks- oder Schulquelle und kennzeichnet Familienerinnerungen daneben klar.","context":"Kameruns Geschichten umfassen viele Gemeinschaften und Perspektiven. Familienerinnerung und veröffentlichte historische Belege sind beide wertvoll, aber verschiedene Arten von Quellen; die Zeitleiste benennt sie klar.","materials":["Papier oder Zeitleistenkarten","Eine vertrauenswürdige Museums-, Archiv-, Bibliotheks- oder Schulquelle","Von der Familie erlaubte Erinnerungen"],"guidance":"Erwachsene wählen altersgerechtes Material, besonders zu Kolonialismus, Konflikt oder Vertreibung. Bittet niemanden, schmerzhafte Ereignisse erneut zu durchleben, und haltet sensible Daten oder Orte privat.","attribution":"Notiert Titel und Institution jeder öffentlichen Quelle und nennt Familienbeiträge nur mit Einwilligung; kennzeichnet Unsicherheit ausdrücklich.","reflection":"Welche Familienerinnerung hat euer Verständnis eines öffentlichen Ereignisses verändert, und welche Quelle würdet ihr als Nächstes erkunden?","steps":[{"position":1,"title":"Einen kleinen Zeitraum wählen","description":"Wählt ein überschaubares Zeitfenster und eine Frage, statt eine vollständige Nationalgeschichte zu versuchen."},{"position":2,"title":"Öffentliche Quellen finden","description":"Nutzt zwei oder drei altersgerechte Quellen aus Museum, Archiv, Bibliothek oder Schule und notiert die Herkunft jeder Aussage."},{"position":3,"title":"Familienerinnerung ergänzen","description":"Ladet optional zu einer Familienerinnerung ein und kennzeichnet sie getrennt von veröffentlichten historischen Belegen."},{"position":4,"title":"Zeitleiste prüfen","description":"Sucht fehlende Perspektiven, markiert offene Fragen und speichert eine Reflexion ohne sensible persönliche Details."}]},
  {"slug":"cameroon-history-family-timeline","locale":"fr","title":"Créer une frise de l'histoire familiale camerounaise","summary":"Placez des souvenirs familiaux à côté d'événements publics soigneusement sourcés sans faire de l'histoire d'une famille l'histoire nationale.","description":"Choisissez une courte période liée à votre famille, ajoutez deux ou trois événements historiques publics provenant d'un musée, d'archives, d'une bibliothèque ou d'une source scolaire de confiance, puis placez les souvenirs familiaux à côté avec des étiquettes claires.","context":"Les histoires du Cameroun comprennent de nombreuses communautés et perspectives. Les souvenirs familiaux et les sources historiques publiées sont précieux mais différents ; la frise les identifie clairement.","materials":["Papier ou cartes de frise","Source fiable de musée, archives, bibliothèque ou école","Souvenirs approuvés par la famille"],"guidance":"Les adultes choisissent du contenu adapté à l'âge, surtout concernant colonialisme, conflit ou déplacement. Ne demandez pas à des proches de revivre des événements douloureux et gardez privées les dates ou lieux sensibles.","attribution":"Notez le titre et l'institution de chaque source publique, ne nommez les contributeurs familiaux qu'avec leur consentement et indiquez explicitement les incertitudes.","reflection":"Quel souvenir familial a changé votre compréhension d'un événement public et quelle source explorerez-vous ensuite ?","steps":[{"position":1,"title":"Choisir une courte période","description":"Choisissez une période accessible et une question plutôt que de tenter une histoire nationale complète."},{"position":2,"title":"Trouver des sources publiques","description":"Utilisez deux ou trois sources adaptées à l'âge issues d'un musée, d'archives, d'une bibliothèque ou d'une école et notez chaque origine."},{"position":3,"title":"Ajouter un souvenir familial","description":"Invitez facultativement un souvenir familial et distinguez-le des éléments historiques publiés."},{"position":4,"title":"Relire la frise","description":"Repérez les perspectives absentes, marquez les questions ouvertes et gardez une réflexion sans détail personnel sensible."}]},
  {"slug":"bamileke-family-celebration","locale":"de","title":"Eine Bamiléké-Familienfeier dokumentieren","summary":"Erkundet, wie eine Bamiléké-Familie einen wichtigen Anlass begeht und was privat bleiben soll.","description":"Wählt einen Anlass, über den eine vertraute Bamiléké-Familienquelle sprechen möchte. Lernt Vorbereitungen, Menschen, Gegenstände, Essen, Sprache oder Musik kennen und erkennt Unterschiede zwischen Bamiléké-Gemeinschaften und Haushalten an.","context":"Bamiléké ist keine einheitliche Haushaltstradition. Diese Aktivität dokumentiert die Darstellung einer Familie und vermeidet Verallgemeinerungen über private, heilige oder gemeinschaftsspezifische Praktiken.","materials":["Eine vertraute Familienquelle","Papier oder eine private Familiennotiz","Optional ein von der Familie erlaubter Gegenstand oder ein Foto"],"guidance":"Die Quelle wählt Anlass und Privatsphäregrenze. Spielt keine heiligen Rollen, Kleidung, Gegenstände oder Zeremonien nach und ladet keine identifizierbaren Bilder ohne Einwilligung hoch.","attribution":"Beschreibt dies als Darstellung der benannten Familie, nennt Mitwirkende mit Erlaubnis und notiert jedes Element, das privat bleiben soll.","reflection":"Welche Vorbereitung oder welcher Wert ist in der Darstellung eurer Familie am wichtigsten, und was sollen spätere Leser über die Privatsphäre verstehen?","steps":[{"position":1,"title":"Einen Anlass wählen","description":"Lasst die Familienquelle einen Anlass wählen und erklären, was Kinder darüber lernen dürfen."},{"position":2,"title":"Vorbereitung kartieren","description":"Listet einige Vorbereitungen oder Rollen auf, ohne eingeschränktes zeremonielles Wissen nachzuahmen."},{"position":3,"title":"Familienvielfalt wahrnehmen","description":"Fragt, was zu diesem Haushalt oder dieser Gemeinschaft gehört und nicht verallgemeinert werden soll."},{"position":4,"title":"Respektvoll bewahren","description":"Speichert eine erlaubte Erinnerung, die Nennung und eine klare Grenze für das Teilen."}]},
  {"slug":"bamileke-family-celebration","locale":"fr","title":"Documenter une célébration familiale bamiléké","summary":"Explorez comment une famille bamiléké marque une occasion importante et ce qui doit rester privé.","description":"Choisissez une occasion qu'une source familiale bamiléké de confiance accepte d'aborder. Découvrez préparatifs, personnes, objets, nourriture, langue ou musique, tout en reconnaissant les variations entre communautés et foyers bamiléké.","context":"Bamiléké ne désigne pas une tradition domestique unique et uniforme. Cette activité documente le récit d'une famille et évite de généraliser des pratiques privées, sacrées ou propres à une communauté.","materials":["Source familiale de confiance","Papier ou note familiale privée","Objet ou photo approuvé par la famille, si souhaité"],"guidance":"La source choisit l'occasion et la limite de confidentialité. Ne rejouez pas comme un jeu des rôles, vêtements, objets ou cérémonies sacrés et ne téléversez aucune image identifiable sans consentement.","attribution":"Présentez cela comme le récit de la famille nommée, citez les personnes avec permission et notez tout élément qui doit rester privé.","reflection":"Quelle préparation ou valeur compte le plus dans le récit de votre famille et que doivent comprendre les futurs lecteurs sur sa confidentialité ?","steps":[{"position":1,"title":"Choisir une occasion","description":"Laissez la source familiale choisir une occasion et expliquer ce que les enfants peuvent apprendre."},{"position":2,"title":"Décrire les préparatifs","description":"Listez quelques préparatifs ou rôles sans reproduire des savoirs cérémoniels restreints."},{"position":3,"title":"Observer les variations familiales","description":"Demandez ce qui appartient à ce foyer ou à cette communauté et ne doit pas être généralisé."},{"position":4,"title":"Conserver avec respect","description":"Gardez un souvenir autorisé, l'attribution et une limite de partage explicite."}]},
  {"slug":"beti-words-and-family-values","locale":"de","title":"Beti-Wörter für Familienwerte erkunden","summary":"Fragt eine vertraute Beti-sprechende Person, wie bestimmte Wörter Werte in ihrer Familie und Sprache ausdrücken.","description":"Wählt zwei oder drei Werte, über die eure Familie spricht, und fragt eine vertraute Beti-sprechende Person nach verwandten Wörtern, Ausdrücken oder Geschichten in der konkreten Sprache, die sie spricht. Macht Übersetzungsunsicherheit sichtbar.","context":"Beti umfasst unterschiedliche Menschen und Sprachen; weder ein Wort noch ein Wert hat eine einzige universelle Familienbedeutung. Die sprechende Person benennt ihre Sprache und erklärt ihren eigenen Gebrauch.","materials":["Eine vertraute Beti-sprechende Person","Karten oder Zettel mit Werten","Eine private Familiennotiz"],"guidance":"Prüft oder korrigiert die sprechende Person nicht mit automatischer Übersetzung. Kinder dürfen eine Deutung anders sehen; nutzt den Unterschied für ein respektvolles Gespräch, nicht als Loyalitätstest.","attribution":"Notiert den bevorzugten Sprachnamen der sprechenden Person, ihre Erklärung und Unsicherheiten; nennt sie nur in der erlaubten Form.","reflection":"Welches Wort oder welche Erklärung war bedeutsam, und wie lebt—oder hinterfragt—eure Familie diesen Wert heute?","steps":[{"position":1,"title":"Familienwerte wählen","description":"Wählt zwei oder drei Werte, ohne zu behaupten, sie definierten jede Beti- oder kamerunische Familie."},{"position":2,"title":"Die Sprache benennen","description":"Fragt, welche konkrete Sprache oder Varietät die Person verwendet, bevor ihr über Wörter sprecht."},{"position":3,"title":"Gebrauch erkunden","description":"Fragt, wann Wort oder Ausdruck verwendet wird und ob eine direkte deutsche, französische oder englische Übersetzung etwas verliert."},{"position":4,"title":"Gemeinsam reflektieren","description":"Speichert die erlaubte Formulierung, die Erklärung der Person und die Antwort eurer Familie."}]},
  {"slug":"beti-words-and-family-values","locale":"fr","title":"Explorer des mots beti pour les valeurs familiales","summary":"Demandez à une personne parlant beti de confiance comment certains mots expriment des valeurs dans sa famille et sa langue.","description":"Choisissez deux ou trois valeurs dont votre famille parle, puis demandez à une personne parlant beti de confiance s'il existe des mots, expressions ou récits associés dans la langue précise qu'elle parle. Rendez visible toute incertitude de traduction.","context":"Beti comprend des peuples et des langues distincts ; ni un mot ni une valeur n'a un sens familial universel. La personne qui parle nomme sa langue et explique son propre usage.","materials":["Personne de confiance parlant beti","Cartes ou papiers de valeurs","Note familiale privée"],"guidance":"N'utilisez pas de traduction automatique pour tester ou corriger la personne qui parle. Les enfants peuvent ne pas partager une interprétation ; faites-en une discussion respectueuse, pas une épreuve de loyauté.","attribution":"Notez le nom de langue préféré de la personne, son explication et toute incertitude ; ne la citez que sous la forme qu'elle autorise.","reflection":"Quel mot ou quelle explication vous a touché, et comment votre famille pratique-t-elle—ou questionne-t-elle—cette valeur aujourd'hui ?","steps":[{"position":1,"title":"Choisir les valeurs familiales","description":"Choisissez deux ou trois valeurs sans prétendre qu'elles définissent toutes les familles beti ou camerounaises."},{"position":2,"title":"Nommer la langue","description":"Demandez quelle langue ou variété précise est utilisée avant de discuter des mots."},{"position":3,"title":"Explorer l'usage","description":"Demandez quand le mot ou l'expression est employé et si une traduction directe en allemand, français ou anglais perd quelque chose."},{"position":4,"title":"Réfléchir ensemble","description":"Conservez la formulation autorisée, l'explication de la personne et la réponse de votre famille."}]},
  {"slug":"grandparent-heritage-interview","locale":"de","title":"Ein Familiengespräch mit Großeltern oder älteren Angehörigen führen","summary":"Bereitet ein Gespräch mit Einwilligung vor, das die Erinnerungen einer älteren Person bewahrt, ohne sie als Stimme für alle zu drängen.","description":"Ladet Großeltern, eine ältere Person oder eine vertraute ältere verwandte Person ein, eine Erinnerung zu Sprache, Kindheit, Familie, Ort, Essen oder Feier auszuwählen. Die Person darf jede Frage auslassen und entscheidet, ob Notizen oder Aufnahmen behalten werden.","context":"Eine ältere Person ist Quelle für ihr eigenes Leben und Wissen, nicht Sprecherin für ganz Kamerun. Erinnerungen können unvollständig sein oder sich verändern; das mindert ihren Familienwert nicht.","materials":["Drei bis fünf freiwillige Fragen","Einen ruhigen Gesprächsort","Papier oder Aufnahmegerät, nur mit Erlaubnis"],"guidance":"Holt vor Beginn und erneut vor dem Speichern oder Teilen Einwilligung ein. Vermeidet Fragen zu Trauma, Konflikt, Aufenthaltsstatus, Gesundheit oder Migration, außer die ältere Person bringt sie selbst ein und möchte fortfahren.","attribution":"Lasst die ältere Person entscheiden, wie sie genannt wird, welche Gemeinschaftsbezüge festgehalten werden und wer das Ergebnis hören oder lesen darf.","reflection":"Was wollte die ältere Person besonders an jüngere Familienmitglieder weitergeben, und wie sollt ihr die Geschichte schützen?","steps":[{"position":1,"title":"Einladen, nicht zuweisen","description":"Erklärt die Aktivität, bietet Themen an und macht klar, dass Ablehnen oder Aufhören jederzeit willkommen ist."},{"position":2,"title":"Erlaubnisse bestätigen","description":"Vereinbart vor Beginn, ob Notizen, Aufnahme, Zitate, privates Speichern oder Teilen in der Familie erlaubt sind."},{"position":3,"title":"Einer Erinnerung zuhören","description":"Stellt einige offene Fragen, lasst Stille zu und folgt der gewählten Richtung ohne Daten oder Beweise zu verlangen."},{"position":4,"title":"Die Geschichte zurückgeben","description":"Zeigt oder lest vor, was ihr bewahrt habt, ändert es auf Wunsch und notiert die endgültige Freigabegrenze."}]},
  {"slug":"grandparent-heritage-interview","locale":"fr","title":"Créer un entretien patrimonial avec un grand-parent ou un aîné","summary":"Préparez un échange fondé sur le consentement qui préserve les souvenirs d'un aîné sans lui demander de représenter tout le monde.","description":"Invitez un grand-parent, un aîné ou un proche plus âgé de confiance à choisir un souvenir sur la langue, l'enfance, la famille, un lieu, la nourriture ou une célébration. La personne peut passer toute question et contrôle la conservation des notes ou enregistrements.","context":"Un aîné est une source pour sa propre vie et ses connaissances, non un porte-parole de tout le Cameroun. La mémoire peut être partielle ou évoluer, ce qui n'en réduit pas la valeur familiale.","materials":["Trois à cinq questions facultatives","Espace calme pour échanger","Papier ou enregistreur utilisé seulement avec permission"],"guidance":"Obtenez le consentement avant de commencer puis avant de conserver ou partager. Évitez les questions sur traumatisme, conflit, statut juridique, santé ou migration, sauf si l'aîné les introduit librement et souhaite continuer.","attribution":"Laissez l'aîné choisir comment le nommer, quels liens communautaires conserver et qui peut entendre ou lire le résultat.","reflection":"Que souhaitait surtout transmettre l'aîné aux plus jeunes et comment vous a-t-il demandé de prendre soin de cette histoire ?","steps":[{"position":1,"title":"Inviter sans imposer","description":"Expliquez l'activité, proposez des thèmes et précisez qu'il est toujours possible de refuser ou d'arrêter."},{"position":2,"title":"Confirmer les permissions","description":"Convenez avant de commencer si vous pouvez prendre des notes, enregistrer, citer, conserver en privé ou partager en famille."},{"position":3,"title":"Écouter un souvenir","description":"Posez quelques questions ouvertes, laissez du silence et suivez la direction choisie sans exiger de dates ou de preuves."},{"position":4,"title":"Restituer l'histoire","description":"Montrez ou relisez ce qui a été conservé, apportez les changements demandés et notez la limite finale de partage."}]}
]
$content$::jsonb;
begin
  for mission_draft in select value from jsonb_array_elements(content)
  loop
    insert into public.cultural_mission_translations (
      mission_id, locale, content_version, source_locale, review_status, reviewed_at,
      reviewed_by, title, summary, description, cultural_context, materials,
      guardian_guidance, respectful_attribution, passport_reflection_prompt
    )
    select mission.id, mission_draft->>'locale', mission.content_version,
      'en', 'needs_review', null, null, mission_draft->>'title',
      mission_draft->>'summary', mission_draft->>'description',
      mission_draft->>'context', array(select jsonb_array_elements_text(mission_draft->'materials')),
      mission_draft->>'guidance', mission_draft->>'attribution', mission_draft->>'reflection'
    from public.cultural_missions mission
    where mission.slug = mission_draft->>'slug'
      and mission.active and mission.review_status = 'reviewed'
    on conflict (mission_id, locale, content_version) do update set
      source_locale = excluded.source_locale,
      review_status = 'needs_review',
      reviewed_at = null,
      reviewed_by = null,
      title = excluded.title,
      summary = excluded.summary,
      description = excluded.description,
      cultural_context = excluded.cultural_context,
      materials = excluded.materials,
      guardian_guidance = excluded.guardian_guidance,
      respectful_attribution = excluded.respectful_attribution,
      passport_reflection_prompt = excluded.passport_reflection_prompt,
      updated_at = now();

    for step_draft in select value from jsonb_array_elements(mission_draft->'steps')
    loop
      insert into public.mission_step_translations (
        step_id, locale, content_version, source_locale, review_status, reviewed_at,
        reviewed_by, title, description
      )
      select step.id, mission_draft->>'locale', mission.content_version,
        'en', 'needs_review', null, null, step_draft->>'title', step_draft->>'description'
      from public.cultural_missions mission
      join public.mission_steps step on step.mission_id = mission.id
      where mission.slug = mission_draft->>'slug'
        and step.position = (step_draft->>'position')::smallint
        and mission.active and mission.review_status = 'reviewed'
      on conflict (step_id, locale, content_version) do update set
        source_locale = excluded.source_locale,
        review_status = 'needs_review',
        reviewed_at = null,
        reviewed_by = null,
        title = excluded.title,
        description = excluded.description,
        updated_at = now();
    end loop;
  end loop;
end
$drafts$;

insert into kinavela_private.schema_migrations(version)
values ('202608130027_cultural_mission_translation_drafts')
on conflict (version) do nothing;

notify pgrst, 'reload schema';

commit;
