import type { Locale } from "@/lib/i18n/config";

export const rootsCopy = {
  de: {
    nav: "Roots Passport",
    eyebrow: "PRIVATE FAMILIENGESCHICHTE",
    title: "Meine Wurzeln",
    intro:
      "Bewahrt Sprache, Erinnerungen und kulturelle Momente für eure Familie – privat und unter eurer Kontrolle.",
    back: "Zurück",
    children: "Kinder",
    entries: "Einträge",
    noEntries: "Noch keine Erinnerungen gesammelt.",
    add: "Erinnerung hinzufügen",
    save: "Speichern",
    saving: "Wird gespeichert…",
    cancel: "Abbrechen",
    type: "Kategorie",
    titleLabel: "Titel",
    description: "Beschreibung",
    occurred: "Datum",
    visibility: "Sichtbarkeit",
    private: "Nur Guardians",
    family: "Familie",
    village: "Geteiltes Village",
    mission: "Abgeschlossene Mission (optional)",
    noMission: "Keine Mission verknüpfen",
    export: "Export anfordern",
    exporting: "Export wird vorbereitet…",
    exportQueued:
      "Export angefordert. Er wird sicher im Hintergrund vorbereitet.",
    delete: "Löschen",
    deleting: "Wird gelöscht…",
    media: "Foto oder Audio (optional)",
    mediaHelp: "Privat gespeichert, maximal 25 MB.",
    attached: "Privates Medium angehängt",
    privacy:
      "Einträge sind standardmäßig privat. Kinder haben keine eigenen Konten.",
    unavailable: "Das Passport ist vorübergehend nicht verfügbar.",
    actionError:
      "Diese Aktion konnte nicht abgeschlossen werden. Bitte erneut versuchen.",
    types: {
      language: "Sprache",
      story: "Geschichte",
      recipe: "Rezept",
      place: "Ort",
      tradition: "Tradition",
      event: "Ereignis",
      family_memory: "Familienerinnerung",
      achievement: "Erfolg",
      trip: "Reise",
      photo: "Foto",
      audio: "Audio",
      video: "Video",
      document: "Dokument",
    },
  },
  fr: {
    nav: "Roots Passport",
    eyebrow: "HISTOIRE FAMILIALE PRIVÉE",
    title: "Mes racines",
    intro:
      "Conservez langue, souvenirs et moments culturels pour votre famille, en privé et sous votre contrôle.",
    back: "Retour",
    children: "Enfants",
    entries: "Entrées",
    noEntries: "Aucun souvenir n’a encore été conservé.",
    add: "Ajouter un souvenir",
    save: "Enregistrer",
    saving: "Enregistrement…",
    cancel: "Annuler",
    type: "Catégorie",
    titleLabel: "Titre",
    description: "Description",
    occurred: "Date",
    visibility: "Visibilité",
    private: "Guardians uniquement",
    family: "Famille",
    village: "Village partagé",
    mission: "Mission terminée (facultatif)",
    noMission: "Aucune mission",
    export: "Demander un export",
    exporting: "Préparation de l’export…",
    exportQueued:
      "Export demandé. Il sera préparé de manière sécurisée en arrière-plan.",
    delete: "Supprimer",
    deleting: "Suppression…",
    media: "Photo ou audio (facultatif)",
    mediaHelp: "Stocké en privé, 25 Mo maximum.",
    attached: "Média privé joint",
    privacy:
      "Les entrées sont privées par défaut. Les enfants n’ont pas de compte propre.",
    unavailable: "Le Passport est temporairement indisponible.",
    actionError: "Cette action n’a pas pu être effectuée. Veuillez réessayer.",
    types: {
      language: "Langue",
      story: "Récit",
      recipe: "Recette",
      place: "Lieu",
      tradition: "Tradition",
      event: "Événement",
      family_memory: "Souvenir familial",
      achievement: "Accomplissement",
      trip: "Voyage",
      photo: "Photo",
      audio: "Audio",
      video: "Vidéo",
      document: "Document",
    },
  },
  en: {
    nav: "Roots Passport",
    eyebrow: "PRIVATE FAMILY HISTORY",
    title: "My roots",
    intro:
      "Keep language, memories and cultural moments for your family—private and under your control.",
    back: "Back",
    children: "Children",
    entries: "Entries",
    noEntries: "No memories have been collected yet.",
    add: "Add a memory",
    save: "Save",
    saving: "Saving…",
    cancel: "Cancel",
    type: "Category",
    titleLabel: "Title",
    description: "Description",
    occurred: "Date",
    visibility: "Visibility",
    private: "Guardians only",
    family: "Family",
    village: "Shared Village",
    mission: "Completed mission (optional)",
    noMission: "No mission link",
    export: "Request export",
    exporting: "Preparing export…",
    exportQueued:
      "Export requested. It will be prepared securely in the background.",
    delete: "Delete",
    deleting: "Deleting…",
    media: "Photo or audio (optional)",
    mediaHelp: "Stored privately, maximum 25 MB.",
    attached: "Private media attached",
    privacy:
      "Entries are private by default. Children do not have their own accounts.",
    unavailable: "The Passport is temporarily unavailable.",
    actionError: "This action could not be completed. Please try again.",
    types: {
      language: "Language",
      story: "Story",
      recipe: "Recipe",
      place: "Place",
      tradition: "Tradition",
      event: "Event",
      family_memory: "Family memory",
      achievement: "Achievement",
      trip: "Trip",
      photo: "Photo",
      audio: "Audio",
      video: "Video",
      document: "Document",
    },
  },
} as const;

export type RootsCopy = (typeof rootsCopy)[Locale];
export function getRootsCopy(locale: Locale) {
  return rootsCopy[locale];
}
