import type { Locale } from "@/lib/i18n/config";

export const rootsCopy = {
  de: {
    nav: "Roots Passport",
    eyebrow: "PRIVATE FAMILIENGESCHICHTE",
    title: "Meine Wurzeln",
    intro:
      "Bewahrt Sprache, Erinnerungen und kulturelle Momente für eure Familie – privat und unter eurer Kontrolle.",
    back: "Zurück",
    children: "Kinder",
    entries: "Einträge",
    noEntries: "Noch keine Erinnerungen gesammelt.",
    add: "Erinnerung hinzufügen",
    save: "Speichern",
    saving: "Wird gespeichert…",
    cancel: "Abbrechen",
    type: "Kategorie",
    titleLabel: "Titel",
    description: "Beschreibung",
    occurred: "Datum",
    visibility: "Sichtbarkeit",
    private: "Nur Guardians",
    family: "Familie",
    village: "Geteiltes Village",
    mission: "Abgeschlossene Mission (optional)",
    noMission: "Keine Mission verknüpfen",
    culture: "Kultur (optional)",
    noCulture: "Keine Kultur verknüpfen",
    language: "Sprache (optional)",
    noLanguage: "Keine Sprache verknüpfen",
    event: "Village-Event (optional)",
    noEvent: "Kein Event verknüpfen",
    sharedVillage: "Ausgewähltes Village",
    chooseVillage: "Village auswählen",
    export: "Export anfordern",
    exporting: "Export wird vorbereitet…",
    exportQueued:
      "Export angefordert. Er wird sicher im Hintergrund vorbereitet.",
    downloadExport: "Herunterladen",
    retry: "Erneut versuchen",
    exportStatuses: {
      queued: "Export wartet",
      processing: "Export wird erstellt",
      ready: "Export ist bereit",
      failed: "Export fehlgeschlagen",
      expired: "Export abgelaufen",
    },
    edit: "Bearbeiten",
    openMedia: "Medium öffnen",
    addMedia: "Medium hinzufügen",
    replaceMedia: "Medium ersetzen",
    deleteMedia: "Medium löschen",
    confirmEntryDelete:
      "Diesen Passport-Eintrag und sein Medium dauerhaft löschen?",
    confirmMediaDelete: "Das angehängte Medium dauerhaft löschen?",
    visibilityLabels: {
      private: "Nur Guardians",
      family: "Familie",
      village: "Ausgewähltes Village",
    },
    delete: "Löschen",
    deleting: "Wird gelöscht…",
    media: "Foto, Audio, Video oder PDF (optional)",
    mediaHelp:
      "Privat gespeichert, maximal 25 MB. Zugriff nur über kurzlebige signierte Links.",
    attached: "Privates Medium angehängt",
    privacy:
      "Einträge sind standardmäßig privat. Kinder haben keine eigenen Konten.",
    unavailable: "Das Passport ist vorübergehend nicht verfügbar.",
    actionError:
      "Diese Aktion konnte nicht abgeschlossen werden. Bitte erneut versuchen.",
    types: {
      language: "Sprache",
      story: "Geschichte",
      recipe: "Rezept",
      place: "Ort",
      tradition: "Tradition",
      event: "Ereignis",
      family_memory: "Familienerinnerung",
      achievement: "Erfolg",
      trip: "Reise",
      photo: "Foto",
      audio: "Audio",
      video: "Video",
      document: "Dokument",
    },
  },
  fr: {
    nav: "Roots Passport",
    eyebrow: "HISTOIRE FAMILIALE PRIVÉE",
    title: "Mes racines",
    intro:
      "Conservez langue, souvenirs et moments culturels pour votre famille, en privé et sous votre contrôle.",
    back: "Retour",
    children: "Enfants",
    entries: "Entrées",
    noEntries: "Aucun souvenir n’a encore été conservé.",
    add: "Ajouter un souvenir",
    save: "Enregistrer",
    saving: "Enregistrement…",
    cancel: "Annuler",
    type: "Catégorie",
    titleLabel: "Titre",
    description: "Description",
    occurred: "Date",
    visibility: "Visibilité",
    private: "Guardians uniquement",
    family: "Famille",
    village: "Village partagé",
    mission: "Mission terminée (facultatif)",
    noMission: "Aucune mission",
    culture: "Culture (facultatif)",
    noCulture: "Aucune culture liée",
    language: "Langue (facultatif)",
    noLanguage: "Aucune langue liée",
    event: "Événement du Village (facultatif)",
    noEvent: "Aucun événement lié",
    sharedVillage: "Village sélectionné",
    chooseVillage: "Choisir un Village",
    export: "Demander un export",
    exporting: "Préparation de l’export…",
    exportQueued:
      "Export demandé. Il sera préparé de manière sécurisée en arrière-plan.",
    downloadExport: "Télécharger",
    retry: "Réessayer",
    exportStatuses: {
      queued: "Export en attente",
      processing: "Export en préparation",
      ready: "Export prêt",
      failed: "Échec de l’export",
      expired: "Export expiré",
    },
    edit: "Modifier",
    openMedia: "Ouvrir le média",
    addMedia: "Ajouter un média",
    replaceMedia: "Remplacer le média",
    deleteMedia: "Supprimer le média",
    confirmEntryDelete: "Supprimer définitivement cette entrée et son média ?",
    confirmMediaDelete: "Supprimer définitivement le média joint ?",
    visibilityLabels: {
      private: "Guardians uniquement",
      family: "Famille",
      village: "Village sélectionné",
    },
    delete: "Supprimer",
    deleting: "Suppression…",
    media: "Photo, audio, vidéo ou PDF (facultatif)",
    mediaHelp:
      "Stocké en privé, 25 Mo maximum. Accès par liens signés de courte durée.",
    attached: "Média privé joint",
    privacy:
      "Les entrées sont privées par défaut. Les enfants n’ont pas de compte propre.",
    unavailable: "Le Passport est temporairement indisponible.",
    actionError: "Cette action n’a pas pu être effectuée. Veuillez réessayer.",
    types: {
      language: "Langue",
      story: "Récit",
      recipe: "Recette",
      place: "Lieu",
      tradition: "Tradition",
      event: "Événement",
      family_memory: "Souvenir familial",
      achievement: "Accomplissement",
      trip: "Voyage",
      photo: "Photo",
      audio: "Audio",
      video: "Vidéo",
      document: "Document",
    },
  },
  en: {
    nav: "Roots Passport",
    eyebrow: "PRIVATE FAMILY HISTORY",
    title: "My roots",
    intro:
      "Keep language, memories and cultural moments for your family—private and under your control.",
    back: "Back",
    children: "Children",
    entries: "Entries",
    noEntries: "No memories have been collected yet.",
    add: "Add a memory",
    save: "Save",
    saving: "Saving…",
    cancel: "Cancel",
    type: "Category",
    titleLabel: "Title",
    description: "Description",
    occurred: "Date",
    visibility: "Visibility",
    private: "Guardians only",
    family: "Family",
    village: "Shared Village",
    mission: "Completed mission (optional)",
    noMission: "No mission link",
    culture: "Culture (optional)",
    noCulture: "No culture link",
    language: "Language (optional)",
    noLanguage: "No language link",
    event: "Village event (optional)",
    noEvent: "No event link",
    sharedVillage: "Selected Village",
    chooseVillage: "Choose a Village",
    export: "Request export",
    exporting: "Preparing export…",
    exportQueued:
      "Export requested. It will be prepared securely in the background.",
    downloadExport: "Download",
    retry: "Retry",
    exportStatuses: {
      queued: "Export queued",
      processing: "Export processing",
      ready: "Export ready",
      failed: "Export failed",
      expired: "Export expired",
    },
    edit: "Edit",
    openMedia: "Open media",
    addMedia: "Add media",
    replaceMedia: "Replace media",
    deleteMedia: "Delete media",
    confirmEntryDelete: "Permanently delete this Passport entry and its media?",
    confirmMediaDelete: "Permanently delete the attached media?",
    visibilityLabels: {
      private: "Guardians only",
      family: "Family",
      village: "Selected Village",
    },
    delete: "Delete",
    deleting: "Deleting…",
    media: "Photo, audio, video or PDF (optional)",
    mediaHelp:
      "Stored privately, maximum 25 MB. Access uses short-lived signed links.",
    attached: "Private media attached",
    privacy:
      "Entries are private by default. Children do not have their own accounts.",
    unavailable: "The Passport is temporarily unavailable.",
    actionError: "This action could not be completed. Please try again.",
    types: {
      language: "Language",
      story: "Story",
      recipe: "Recipe",
      place: "Place",
      tradition: "Tradition",
      event: "Event",
      family_memory: "Family memory",
      achievement: "Achievement",
      trip: "Trip",
      photo: "Photo",
      audio: "Audio",
      video: "Video",
      document: "Document",
    },
  },
} as const;

export type RootsCopy = (typeof rootsCopy)[Locale];
export function getRootsCopy(locale: Locale) {
  return rootsCopy[locale];
}
